EU27_CODES = [
    "AT",
    "BE",
    "BG",
    "HR",
    "CY",
    "CZ",
    "DK",
    "EE",
    "FI",
    "FR",
    "DE",
    "GR",
    "HU",
    "IE",
    "IT",
    "LV",
    "LT",
    "LU",
    "MT",
    "NL",
    "PL",
    "PT",
    "RO",
    "SK",
    "SI",
    "ES",
    "SE",
]

EUROSTAT_INDICATORS = [
    {
        "indicator_id": "estat_hpi_total_i15_q",
        "indicator_name": "Indice prezzi case (2015=100, totale abitazioni)",
        "dataset_code": "prc_hpi_q",
        "unit": "indice 2015=100",
        "frequency": "Q",
        "source": "Eurostat",
        "theme": "prezzi",
        "filters": {"freq": "Q", "purchase": "TOTAL", "unit": "I15_Q"},
    },
    {
        "indicator_id": "estat_net_earnings_aw100_eur_a",
        "indicator_name": "Retribuzione netta annua (single, no figli, 100% salario medio)",
        "dataset_code": "earn_nt_net",
        "unit": "EUR",
        "frequency": "A",
        "source": "Eurostat",
        "theme": "redditi",
        "filters": {"freq": "A", "currency": "EUR", "estruct": "NET", "ecase": "P1_NCH_AW100"},
    },
    {
        "indicator_id": "estat_housing_cost_burden_median_a",
        "indicator_name": "Mediana del peso dei costi abitativi sul reddito",
        "dataset_code": "ilc_lvho08a",
        "unit": "% reddito disponibile",
        "frequency": "A",
        "source": "Eurostat affordable housing",
        "theme": "affordability",
        "filters": {"freq": "A", "unit": "PC", "rskpovth": "TOTAL", "age": "TOTAL", "sex": "T"},
    },
    {
        "indicator_id": "estat_housing_overburden_total_pc_a",
        "indicator_name": "Housing cost overburden rate",
        "dataset_code": "ilc_lvho07a",
        "unit": "percentuale popolazione",
        "frequency": "A",
        "source": "Eurostat affordable housing",
        "theme": "affordability",
        "filters": {"freq": "A", "unit": "PC", "rskpovth": "TOTAL", "age": "TOTAL", "sex": "T"},
    },
    {
        "indicator_id": "estat_housing_overburden_tenants_pc_a",
        "indicator_name": "Housing cost overburden rate per inquilini",
        "dataset_code": "ilc_lvho07c",
        "unit": "percentuale popolazione",
        "frequency": "A",
        "source": "Eurostat affordable housing",
        "theme": "affordability",
        "filters": {"freq": "A", "unit": "PC", "tenure": "RENT_MKT"},
    },
    {
        "indicator_id": "estat_arrears_housing_bills_total_a",
        "indicator_name": "Arretrati su mutuo, affitto o bollette",
        "dataset_code": "ilc_mdes05",
        "unit": "percentuale popolazione",
        "frequency": "A",
        "source": "Eurostat affordable housing",
        "theme": "affordability",
        "filters": {"freq": "A", "hhtyp": "TOTAL", "incgrp": "TOTAL", "unit": "PC"},
    },
    {
        "indicator_id": "estat_overcrowding_total_pc_a",
        "indicator_name": "Tasso di sovraffollamento abitativo",
        "dataset_code": "ilc_lvho05a",
        "unit": "percentuale popolazione",
        "frequency": "A",
        "source": "Eurostat affordable housing",
        "theme": "shortage_proxy",
        "filters": {"freq": "A", "unit": "PC", "incgrp": "TOTAL", "age": "TOTAL", "sex": "T"},
    },
    {
        "indicator_id": "estat_severe_housing_deprivation_total_a",
        "indicator_name": "Severe housing deprivation rate",
        "dataset_code": "ilc_mdho06a",
        "unit": "percentuale popolazione",
        "frequency": "A",
        "source": "Eurostat affordable housing",
        "theme": "shortage_proxy",
        "filters": {"freq": "A", "unit": "PC", "rskpovth": "TOTAL", "sex": "T", "age": "TOTAL"},
    },
    {
        "indicator_id": "estat_damp_leaking_dwelling_total_a",
        "indicator_name": "Popolazione in abitazioni con perdite, umidita' o marciume",
        "dataset_code": "ilc_mdho01",
        "unit": "percentuale popolazione",
        "frequency": "A",
        "source": "Eurostat affordable housing",
        "theme": "qualita_stock",
        "filters": {"freq": "A", "hhtyp": "TOTAL", "incgrp": "TOTAL", "unit": "PC", "sex": "T", "age": "TOTAL"},
    },
    {
        "indicator_id": "estat_inability_keep_home_warm_total_a",
        "indicator_name": "Incapacita' di riscaldare adeguatamente la casa",
        "dataset_code": "ilc_mdes01",
        "unit": "percentuale popolazione",
        "frequency": "A",
        "source": "Eurostat affordable housing",
        "theme": "qualita_stock",
        "filters": {"freq": "A", "hhtyp": "TOTAL", "incgrp": "TOTAL", "unit": "PC"},
    },
    {
        "indicator_id": "estat_young_living_with_parents_25_34_a",
        "indicator_name": "Persone 25-34 anni che vivono con i genitori",
        "dataset_code": "ilc_lvps08",
        "unit": "percentuale popolazione 25-34",
        "frequency": "A",
        "source": "Eurostat affordable housing",
        "theme": "domanda_latente",
        "filters": {"freq": "A", "age": "Y25-34", "sex": "T", "unit": "PC"},
    },
    {
        "indicator_id": "estat_age_leaving_parental_home_a",
        "indicator_name": "Eta' media di uscita dalla casa dei genitori",
        "dataset_code": "yth_demo_030",
        "unit": "anni",
        "frequency": "A",
        "source": "Eurostat",
        "theme": "domanda_latente",
        "filters": {"freq": "A", "unit": "AVG", "sex": "T"},
    },
    {
        "indicator_id": "estat_population_total_a",
        "indicator_name": "Popolazione totale al 1 gennaio",
        "dataset_code": "demo_pjan",
        "unit": "persone",
        "frequency": "A",
        "source": "Eurostat",
        "theme": "demografia",
        "filters": {"freq": "A", "unit": "NR", "age": "TOTAL", "sex": "T"},
    },
    {
        "indicator_id": "estat_private_households_total_a",
        "indicator_name": "Famiglie private",
        "dataset_code": "lfst_hhnhtych",
        "unit": "migliaia di famiglie",
        "frequency": "A",
        "source": "Eurostat",
        "theme": "demografia",
        "filters": {"freq": "A", "agechild": "TOTAL", "n_child": "TOTAL", "phhcomp": "TOTAL", "unit": "THS_HH"},
    },
    {
        "indicator_id": "estat_residential_permits_dwellings_ths_a",
        "indicator_name": "Permessi edilizi: nuove abitazioni residenziali",
        "dataset_code": "sts_cobp_a",
        "unit": "migliaia di abitazioni",
        "frequency": "A",
        "source": "Eurostat",
        "theme": "offerta",
        "filters": {
            "freq": "A",
            "indic_bt": "BPRM_DW",
            "cpa2_1": "CPA_F41001_X_410014",
            "s_adj": "NSA",
            "unit": "THS",
        },
    },
    {
        "indicator_id": "estat_residential_permits_floor_area_a",
        "indicator_name": "Permessi edilizi residenziali (m2 per 1.000 abitanti)",
        "dataset_code": "tipsho50",
        "unit": "m2 per 1.000 abitanti",
        "frequency": "A",
        "source": "Eurostat",
        "theme": "offerta",
        "filters": {
            "freq": "A",
            "s_adj": "NSA",
            "unit": "M2_THAB",
            "indic_bt": "BPRM_SQM",
            "cpa2_1": "CPA_F41001",
        },
    },
    {
        "indicator_id": "estat_building_permits_dwellings_index_q",
        "indicator_name": "Permessi di costruzione abitazioni (indice 2021=100)",
        "dataset_code": "sts_cobp_q",
        "unit": "indice 2021=100",
        "frequency": "Q",
        "source": "Eurostat",
        "theme": "offerta",
        "filters": {
            "freq": "Q",
            "indic_bt": "BPRM_DW",
            "cpa2_1": "CPA_F41001_X_410014",
            "s_adj": "SCA",
            "unit": "I21",
        },
    },
    {
        "indicator_id": "estat_construction_production_index_a",
        "indicator_name": "Produzione nelle costruzioni",
        "dataset_code": "sts_copr_a",
        "unit": "indice 2015=100",
        "frequency": "A",
        "source": "Eurostat",
        "theme": "offerta",
        "filters": {"freq": "A", "indic_bt": "PRD", "nace_r2": "F", "s_adj": "CA", "unit": "I15"},
    },
    {
        "indicator_id": "estat_new_residential_construction_cost_i21_q",
        "indicator_name": "Costi di costruzione nuovi edifici residenziali",
        "dataset_code": "sts_copi_q",
        "unit": "indice 2021=100",
        "frequency": "Q",
        "source": "Eurostat",
        "theme": "offerta",
        "filters": {
            "freq": "Q",
            "indic_bt": "COST",
            "cpa2_1": "CPA_F41001_X_410014",
            "s_adj": "NSA",
            "unit": "I21",
        },
    },
    {
        "indicator_id": "estat_gfcf_dwellings_pct_gdp_a",
        "indicator_name": "Investimenti in abitazioni (GFCF, % PIL)",
        "dataset_code": "nama_10_an6",
        "unit": "% PIL",
        "frequency": "A",
        "source": "Eurostat",
        "theme": "investimenti",
        "filters": {"freq": "A", "unit": "PC_GDP", "asset10": "N111G"},
    },
    {
        "indicator_id": "estat_arop_after_housing_costs_a",
        "indicator_name": "Rischio poverta' dopo i costi abitativi",
        "dataset_code": "ilc_li45",
        "unit": "percentuale popolazione",
        "frequency": "A",
        "source": "Eurostat affordable housing",
        "theme": "affordability",
        "filters": {"freq": "A", "sex": "T", "age": "TOTAL", "unit": "PC"},
    },
    {
        "indicator_id": "estat_arop_standard_a",
        "indicator_name": "Rischio poverta' standard",
        "dataset_code": "tespm010",
        "unit": "percentuale popolazione",
        "frequency": "A",
        "source": "Eurostat",
        "theme": "affordability",
        "filters": {"freq": "A", "unit": "PC", "indic_il": "LI_R_MD60", "sex": "T", "age": "TOTAL"},
    },
    {
        "indicator_id": "estat_dwellings_total_2021",
        "indicator_name": "Abitazioni convenzionali totali (censimento 2021)",
        "dataset_code": "cens_21dwop_r3",
        "unit": "abitazioni",
        "frequency": "A",
        "source": "Eurostat census 2021",
        "theme": "stock",
        "filters": {"freq": "A", "housing": "DW", "y_const": "TOTAL", "unit": "NR"},
    },
    {
        "indicator_id": "estat_dwellings_occupied_2021",
        "indicator_name": "Abitazioni convenzionali occupate (censimento 2021)",
        "dataset_code": "cens_21dwop_r3",
        "unit": "abitazioni",
        "frequency": "A",
        "source": "Eurostat census 2021",
        "theme": "stock",
        "filters": {"freq": "A", "housing": "DW_OC", "y_const": "TOTAL", "unit": "NR"},
    },
    {
        "indicator_id": "estat_dwellings_unoccupied_2021",
        "indicator_name": "Abitazioni convenzionali non occupate (censimento 2021)",
        "dataset_code": "cens_21dwop_r3",
        "unit": "abitazioni",
        "frequency": "A",
        "source": "Eurostat census 2021",
        "theme": "stock",
        "filters": {"freq": "A", "housing": "DW_NOC", "y_const": "TOTAL", "unit": "NR"},
    },
    {
        "indicator_id": "estat_dwellings_built_before_1919_2021",
        "indicator_name": "Abitazioni costruite prima del 1919 (censimento 2021)",
        "dataset_code": "cens_21dwop_r3",
        "unit": "abitazioni",
        "frequency": "A",
        "source": "Eurostat census 2021",
        "theme": "eta_stock",
        "filters": {"freq": "A", "housing": "DW", "y_const": "Y_LT1919", "unit": "NR"},
    },
    {
        "indicator_id": "estat_dwellings_built_1919_1945_2021",
        "indicator_name": "Abitazioni costruite tra 1919 e 1945 (censimento 2021)",
        "dataset_code": "cens_21dwop_r3",
        "unit": "abitazioni",
        "frequency": "A",
        "source": "Eurostat census 2021",
        "theme": "eta_stock",
        "filters": {"freq": "A", "housing": "DW", "y_const": "Y1919-1945", "unit": "NR"},
    },
    {
        "indicator_id": "estat_dwellings_built_1946_1960_2021",
        "indicator_name": "Abitazioni costruite tra 1946 e 1960 (censimento 2021)",
        "dataset_code": "cens_21dwop_r3",
        "unit": "abitazioni",
        "frequency": "A",
        "source": "Eurostat census 2021",
        "theme": "eta_stock",
        "filters": {"freq": "A", "housing": "DW", "y_const": "Y1946-1960", "unit": "NR"},
    },
    {
        "indicator_id": "estat_dwellings_built_1961_1980_2021",
        "indicator_name": "Abitazioni costruite tra 1961 e 1980 (censimento 2021)",
        "dataset_code": "cens_21dwop_r3",
        "unit": "abitazioni",
        "frequency": "A",
        "source": "Eurostat census 2021",
        "theme": "eta_stock",
        "filters": {"freq": "A", "housing": "DW", "y_const": "Y1961-1980", "unit": "NR"},
    },
    {
        "indicator_id": "estat_dwellings_built_1981_2000_2021",
        "indicator_name": "Abitazioni costruite tra 1981 e 2000 (censimento 2021)",
        "dataset_code": "cens_21dwop_r3",
        "unit": "abitazioni",
        "frequency": "A",
        "source": "Eurostat census 2021",
        "theme": "eta_stock",
        "filters": {"freq": "A", "housing": "DW", "y_const": "Y1981-2000", "unit": "NR"},
    },
    {
        "indicator_id": "estat_dwellings_built_2001_2010_2021",
        "indicator_name": "Abitazioni costruite tra 2001 e 2010 (censimento 2021)",
        "dataset_code": "cens_21dwop_r3",
        "unit": "abitazioni",
        "frequency": "A",
        "source": "Eurostat census 2021",
        "theme": "eta_stock",
        "filters": {"freq": "A", "housing": "DW", "y_const": "Y2001-2010", "unit": "NR"},
    },
    {
        "indicator_id": "estat_dwellings_built_2011_2015_2021",
        "indicator_name": "Abitazioni costruite tra 2011 e 2015 (censimento 2021)",
        "dataset_code": "cens_21dwop_r3",
        "unit": "abitazioni",
        "frequency": "A",
        "source": "Eurostat census 2021",
        "theme": "eta_stock",
        "filters": {"freq": "A", "housing": "DW", "y_const": "Y2011-2015", "unit": "NR"},
    },
    {
        "indicator_id": "estat_dwellings_built_after_2016_2021",
        "indicator_name": "Abitazioni costruite dal 2016 in poi (censimento 2021)",
        "dataset_code": "cens_21dwop_r3",
        "unit": "abitazioni",
        "frequency": "A",
        "source": "Eurostat census 2021",
        "theme": "eta_stock",
        "filters": {"freq": "A", "housing": "DW", "y_const": "Y_GE2016", "unit": "NR"},
    },
    {
        "indicator_id": "estat_dwellings_built_unknown_2021",
        "indicator_name": "Abitazioni con periodo di costruzione non indicato (censimento 2021)",
        "dataset_code": "cens_21dwop_r3",
        "unit": "abitazioni",
        "frequency": "A",
        "source": "Eurostat census 2021",
        "theme": "eta_stock",
        "filters": {"freq": "A", "housing": "DW", "y_const": "UNK", "unit": "NR"},
    },
]

OECD_INDICATORS = [
    {
        "indicator_id": "oecd_avg_annual_wage_usdppp_a",
        "indicator_name": "Salario medio annuo (USD PPP costanti)",
        "flow": "OECD.ELS.SAE,DSD_EARNINGS@AV_AN_WAGE,1.0",
        "key": "......",
        "unit": "USD PPP",
        "frequency": "A",
        "source": "OECD",
        "theme": "redditi",
        "filters": {"MEASURE": "WG", "UNIT_MEASURE": "USD_PPP", "PRICE_BASE": "Q"},
        "params": {},
    },
    {
        "indicator_id": "oecd_real_house_price_index_q",
        "indicator_name": "Indice reale dei prezzi delle case",
        "flow": "OECD.ECO.MPD,DSD_AN_HOUSE_PRICES@DF_HOUSE_PRICES,1.0",
        "key": "...",
        "unit": "indice",
        "frequency": "Q",
        "source": "OECD",
        "theme": "prezzi",
        "filters": {"MEASURE": "RHP", "UNIT_MEASURE": "IX", "FREQ": "Q"},
        "params": {},
    },
    {
        "indicator_id": "oecd_house_price_to_income_q",
        "indicator_name": "Rapporto prezzi case / reddito",
        "flow": "OECD.ECO.MPD,DSD_AN_HOUSE_PRICES@DF_HOUSE_PRICES,1.0",
        "key": "...",
        "unit": "indice/rapporto",
        "frequency": "Q",
        "source": "OECD",
        "theme": "affordability",
        "filters": {"MEASURE": "HPI_YDH", "FREQ": "Q"},
        "params": {},
    },
    {
        "indicator_id": "oecd_gfcf_dwellings_current_prices_a",
        "indicator_name": "Investimenti in abitazioni (GFCF, prezzi correnti)",
        "flow": "OECD.SDD.NAD,DSD_NASEC10@DF_TABLE14_GFCF,1.1",
        "key": "A..S1.S1.D.P51G.N111G._Z..S.V.N.T0800",
        "unit": "milioni valuta nazionale",
        "frequency": "A",
        "source": "OECD",
        "theme": "investimenti",
        "filters": {"INSTR_ASSET": "N111G", "TRANSACTION": "P51G", "SECTOR": "S1"},
        "params": {"startPeriod": "1995"},
    },
]
